// <auto-generated />
using System;
using DAL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(TripAdvisorContext))]
    [Migration("20210129145139_add-location-opinion-2")]
    partial class addlocationopinion2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DAL.Model.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Opinion");
                });

            modelBuilder.Entity("DAL.Model.Opinion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClientID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Locationid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Locationid");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("DAL.Model.Opinion", b =>
                {
                    b.HasOne("DAL.Model.Location", null)
                        .WithMany("OpinionList")
                        .HasForeignKey("Locationid");
                });

            modelBuilder.Entity("DAL.Model.Location", b =>
                {
                    b.Navigation("OpinionList");
                });
#pragma warning restore 612, 618
        }
    }
}
